version: "3.5"

networks:
  "01":

services:
  influxdb:

    See docker-compose.yml for (totally not secure) usage-examples
    Base software: https://github.com/merbanan/rtl_433
    Tested hardware: https://www.amazon.de/NooElec-NESDR-Mini-USB-Empf%C3%A4nger-Set-Female-SMA-Adapter/dp/B00VZ1AWQA/ref=sr_1_fkmrnull_2_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=sdr+433+stick&qid=1554484622&s=gateway&sr=8-2-fkmrnull-spons&psc=1



    See docker-compose.yml for (totally not secure) usage-examples
    Base software: https://github.com/merbanan/rtl_433
    Tested hardware: https://www.amazon.de/NooElec-NESDR-Mini-USB-Empf%C3%A4nger-Set-Female-SMA-Adapter/dp/B00VZ1AWQA/ref=sr_1_fkmrnull_2_sspa?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=sdr+433+stick&qid=1554484622&s=gateway&sr=8-2-fkmrnull-spons&psc=1


    restart: unless-stopped
    image: influxdb:latest
    networks:
      - "01"
    container_name: influxdb
    hostname: influxdb
    ports:
      - "2003:2003"
      - "8086:8086"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: "true"
      INFLUXDB_DB: "sensors; CREATE DATABASE cadvisor;"
    volumes:
      - /etc/timezone:/etc/timezone
      - /media/usb/influxdb/data/:/var/lib/influxdb/

  grafana:
    restart: unless-stopped
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    networks:
      - "01"
    container_name: grafana
    hostname: grafana
    user: "1000"
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "supersecret"
      GF_USERS_DEFAULT_THEME: "dark"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - /etc/timezone:/etc/timezone
      - ./grafana/data/:/var/lib/grafana/

  cadvisor:
    restart: unless-stopped
    depends_on:
      - influxdb
    image: budry/cadvisor-arm
    networks:
      - "01"
    container_name: cadvisor
    hostname: cadvisor
#   command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone
      - /:/rootfs/:ro
      - /var/run/:/var/run/:rw
      - /sys/:/sys/:ro
      - /var/lib/docker/:/var/lib/docker/:ro

  sdr:
     restart: unless-stopped
     depends_on:
        - influxdb
     image: mboehm21/sdr_receiver:latest
     networks:
       - "01"
     container_name: sdr
     hostname: sdr
     environment:
       SDR_PARAMS: "-G"
       INFLUX_SRV: "influxdb"
       INFLUX_SRV2: "< other influx-db>"
       INFLUX_PORT: "8086"
       INFLUX_USER: ""
       INFLUX_PW: ""
       INFLUX_NAME: "sensors"
       Prologue_TH_SUBTYPE5_ID55: "livingroom"
       Prologue_TH_SUBTYPE5_ID170: "well"
     devices:
        - /dev/bus/usb/001/008
     volumes:
       - /etc/timezone:/etc/timezone:ro
